### PR TITLE
Migrate Elasticsearch examples to JUnit 5

### PR DESCRIPTION
**Pull request by wolfdale**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [x] You submit test cases (unit or integration tests) that back your changes.
- [x] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@wolfdale Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=609)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=609) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@wolfdale Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=609)!

**Comment by mp911de** [comment]
Thanks for your contribution. The changes have an entirely different formatting/import order. Please use the Spring Data formatting settings if you plan to use auto-reformat, see https://github.com/spring-projects/spring-data-build/tree/master/etc/ide.

Paging @sothawo

**Comment by sothawo** [comment]
When changing the copyright years, please do not replace _2019_ with _2021_, but change it to _2019-2021_.

**Comment by wolfdale** [comment]
Corrected. Apparently I had the correct formatting yesterday when I raised the PR. I made few changes today which messed up the code formatting.

**Comment by mp911de** [comment]
Thank you for your contribution. That's merged and polished now.

**Pull request closed without merging**
