### PR TITLE
Update redis/repositories example to use application.properties config

### LINKED ISSUE #396: Please provide an example folder illustrating how to override the default parameters for spring-data-redis
I am just starting out with spring-data-redis using lettuce and I can't seem to get the autowired objects to pick up `spring.redis.host` from my application.yml.

```yaml
spring:
  redis:
    host: xxxxxxxxxxx.cache.amazonaws.com
    port: 6379
```
Could you give me some pointers based off [example/springdata/redis/repositories/ApplicationConfiguration.java](https://github.com/spring-projects/spring-data-examples/blob/master/redis/repositories/src/main/java/example/springdata/redis/repositories/ApplicationConfiguration.java#L35)?

### PR DESCRIPTION
**Pull request by Trii**
Modernization no longer requires custom @Bean configuration

Closes #396

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Trii Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=401)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=401) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Trii Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=401)!

**Comment by olivergierke** [comment]
That's polished and merged, thanks!

**Comment by Trii** [comment]
You are welcome. Thanks for merging!

**Pull request closed without merging**
