### PR TITLE
Adding Aerospike to Spring-Data-Example

### PR DESCRIPTION
**Pull request by carosys**

### CODE REVIEW

**Comment by Chidanand-Maligi** [comment]
werwerwer

**Comment by mp911de** [comment]
Thanks for the PR and sorry for the long radio silence. We typically do not include examples for external modules.

**Comment by pivotal-issuemaster** [comment]
@carosys Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=138)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=138) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@carosys Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=138)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=138) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@carosys Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=138)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=138) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Pull request closed without merging**
