### PR TITLE
add GridFS example for spring data

### PR DESCRIPTION
**Pull request by hlang**
provide GridFS example. See issue #218.

### CODE REVIEW

**Comment by hlang** [comment]
Any ideas when this will be merged?

**Comment by olivergierke** [comment]
Thanks for the pointer again. Changes look good. We're just busy preparing a release currently. Will take care of that after that.

**Comment by hlang** [comment]
Updated the gridfs example to spring data 2.0.0.
But not sure if things got more complicated since 2.0.0. 
See [How to get gridFsFile content in spring data mongodb](https://stackoverflow.com/questions/46856387/how-to-get-gridfsfile-content-in-spring-data-mongodb)

**Comment by mp911de** [comment]
That's merged and polished now. Thanks a lot for your contribution.

**Pull request closed without merging**
