### PR TITLE
Migrating examples to junit 5

### PR DESCRIPTION
**Pull request by divyajnu08**
- [ ] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/main/CONTRIBUTING.adoc).
- [ ] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/main/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by divyajnu08** [comment]
Hi Mark

I have migrated all examples except redis since i am finding it difficult , chain of rules in a test.
Could you please guide me ? I am also working on it will raise a PR when fixed.

Thanks

**Comment by divyajnu08** [comment]
There are some conflicts , i will resolve them.

**Comment by mp911de** [comment]
Meanwhile, all samples except Geode are migrated to JUnit 5. Note that we've just merged the migration to Java 16 with #606

**Comment by divyajnu08** [comment]
its already done in base.

**Pull request closed without merging**
