### PR TITLE
Update pom.xml : not "Ingalls-M1" version, change to "Hopper-SR2"

### PR DESCRIPTION
**Pull request by luowenqiang**
Dependency version error : not "Ingalls-M1" version, change to "Hopper-SR2"
<spring-data-releasetrain.version>Ingalls-M1</spring-data-releasetrain.version>  
Change To
<spring-data-releasetrain.version>Hopper-SR2</spring-data-releasetrain.version>

### CODE REVIEW

**Comment by olivergierke** [comment]
Can you elaborate? We refer to `Ingalls-M1` by purpose.

**Comment by luowenqiang** [comment]
Sorry, I was wrong,not add "Spring Milestones" repository.

**Comment by luowenqiang** [comment]
added "Spring Milestones" repository to resolved this problem

**Comment by olivergierke** [comment]
That shouldn't be necessary as the POM [contains the `libs-snapshot` repository](https://github.com/spring-projects/spring-data-examples/blob/master/pom.xml#L120-L125) that aggregates both release, milestone and snapshot artifacts.

**Pull request closed without merging**
