### PR TITLE
Merge pull request #1 from spring-projects/master

### PR DESCRIPTION
**Pull request by anupis**
#351 - Fix and simplify DataAccessStrategy construction.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@anupis Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=357)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=357) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by schauder** [comment]
Closing this because it doesn't contain any changes nor does it explain what it tries to change.

**Comment by pivotal-issuemaster** [comment]
@anupis Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=357)!

**Comment by pivotal-issuemaster** [comment]
@anupis Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-data-examples&pullRequestId=357)!

**Pull request closed without merging**
