### PR TITLE
Migrating jpa and web examples to junit 5.

### PR DESCRIPTION
**Pull request by divyajnu08**
- [x] You have read the [Spring Data contribution guidelines](https://github.com/spring-projects/spring-data-build/blob/master/CONTRIBUTING.adoc).
- [x] You use the code formatters provided [here](https://github.com/spring-projects/spring-data-build/tree/master/etc/ide) and have them applied to your changes. Don’t submit any formatting related changes.
- [ ] You submit test cases (unit or integration tests) that back your changes.
- [ ] You added yourself as author in the headers of the classes you touched. Amend the date range in the Apache license header if needed. For new types, add the license header (copy from another file and set the current year only).

### CODE REVIEW

**Comment by schauder** [comment]
This relates to #583.

**Comment by schauder** [comment]
Thanks. That's polished and merged.

There were some unnecessary changes to the imports which I undid.
You might want to check your formatter settings.

**Comment by divyajnu08** [comment]
Thanks Jens !!  I will take care in future.

**Comment by mp911de** [comment]
On a related note, please make sure that the email address used in your commits either matches your GitHub profile or add the mail address to your GitHub profile. That way the commits will link back to your profile and you'll see these commits in your GitHub contribution graph.

**Comment by divyajnu08** [comment]
> On a related note, please make sure that the email address used in your commits either matches your GitHub profile or add the mail address to your GitHub profile. That way the commits will link back to your profile and you'll see these commits in your GitHub contribution graph.

ok sure

**Pull request closed without merging**
